accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

# from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup")

]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),

]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ExpenseCategoryCreateView,
    ExpenseCategoryListView,
    ReceiptCreateView,
    ReceiptListView,
    AccountCreateView,
    AccountListView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_new"),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path("accounts/create/", AccountCreateView.as_view(), name="account_new"),
    path("categories/", ExpenseCategoryListView.as_view(), name="category_list"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name="category_new",),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.conf import settings
from django.db import models

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField(blank=True)
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from receipts.models import ExpenseCategory, Account, Receipt

# Create your views here.


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_categories/new.html"
    fields = ["name"]
    
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")

class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(owner=self.request.user)

class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/new.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")

class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(owner=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}

<main>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for account in account_list %}
            <tr>
                <td>{{ account.name }}</td>
                <td>{{ account.number }}</td>
                <td>{{ account.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>

{% endblock content %}

receipts/templates/accounts/new.html
{% extends 'base.html' %}



{%block content%}
<main>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button>Create</button>
        </div>
    </form>
</main>
{%endblock content%}

receipts/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <header>
            <nav>
                <a href="{% url 'home' %}">Receipts</a>
                <a href="{% url 'receipt_new' %}">Create Receipts</a>
                <a href="{% url 'account_list' %}">Accounts</a>
                <a href="{% url 'account_new' %}">Create Account</a>
                <a href="{% url 'category_list' %}">Categories</a>
                <a href="{% url 'category_new' %}">Create Category</a>
                <a href="{% url 'logout' %}">Logout</a>
            </nav>
        </header>
        {% block content %}

        {% endblock content %}
    </body>
</html>

receipts/templates/expense_categories/list.html
{% extends 'base.html' %}



{%block content%}
<main>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Nember of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for category in expensecategory_list %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{%endblock content%}

receipts/templates/expense_categories/new.html
{% extends 'base.html' %}



{%block content%}
<main>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button>Create</button>
        </div>
    </form>
</main>
{%endblock content%}

receipts/templates/receipts/list.html
{% extends 'base.html' %}



{%block content%}
<main>
    <table>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for receipt in receipt_list %}
            <tr>
                <td>{{ receipt.vendor }}</td>
                <td>{{ receipt.total }}</td>
                <td>{{ receipt.tax }}</td>
                <td>{{ receipt.date }}</td>
                <td>{{ receipt.category }}</td>
                <td>{{ receipt.account }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{%endblock content%}

receipts/templates/receipts/new.html
{% extends 'base.html' %}



{%block content%}
<main>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button>Create</button>
        </div>
    </form>
</main>
{%endblock content%}